import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import config from "../packages.config.mjs";

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const MODULES_DIR = resolve(ROOT_DIR, config.modulesDirectory);
const PACKAGES_DIR = resolve(ROOT_DIR, config.packagesDirectory);
const VERSIONS_FILE = resolve(ROOT_DIR, "packages.versions.json");

const GENERATED_MARKER = ".raindrops-generated";

function readJson(file) {
  return JSON.parse(readFileSync(file, "utf8"));
}

function writeJson(file, value) {
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

function ensureDirectory(directory) {
  mkdirSync(directory, {
    recursive: true,
  });
}

function getSubdirectories(directory) {
  if (!existsSync(directory)) {
    return [];
  }

  return readdirSync(directory, {
    withFileTypes: true,
  })
    .filter((entry) => entry.isDirectory())
    .map((entry) => resolve(directory, entry.name))
    .sort((a, b) => a.localeCompare(b));
}

function modulePathFromDirectory(directory) {
  return relative(MODULES_DIR, directory).split(sep).join("/");
}

function packageSlugFromModulePath(modulePath) {
  return modulePath.split("/").join(config.naming.separator);
}

function packageNameFromModulePath(modulePath) {
  return `${config.scope}/${packageSlugFromModulePath(modulePath)}`;
}

function isLeafModule(directory) {
  return existsSync(resolve(directory, "src", "index.ts"));
}

function discoverLeafModules(directory = MODULES_DIR) {
  const modules = [];

  for (const child of getSubdirectories(directory)) {
    if (isLeafModule(child)) {
      const modulePath = modulePathFromDirectory(child);

      modules.push({
        type: "leaf",
        directory: child,
        modulePath,
        packageSlug: packageSlugFromModulePath(modulePath),
        packageName: packageNameFromModulePath(modulePath),
      });
    }

    modules.push(...discoverLeafModules(child));
  }

  return modules;
}

function containsLeafModule(directory) {
  for (const child of getSubdirectories(directory)) {
    if (isLeafModule(child)) {
      return true;
    }

    if (containsLeafModule(child)) {
      return true;
    }
  }

  return false;
}

function discoverAggregateModules(directory = MODULES_DIR) {
  const aggregates = [];

  for (const child of getSubdirectories(directory)) {
    if (!isLeafModule(child) && containsLeafModule(child)) {
      const modulePath = modulePathFromDirectory(child);

      aggregates.push({
        type: "aggregate",
        directory: child,
        modulePath,
        packageSlug: packageSlugFromModulePath(modulePath),
        packageName: packageNameFromModulePath(modulePath),
      });

      aggregates.push(...discoverAggregateModules(child));
    }
  }

  return aggregates;
}

function removePreviouslyGeneratedPackage(packageDirectory) {
  const marker = resolve(packageDirectory, GENERATED_MARKER);

  if (!existsSync(marker)) {
    return;
  }

  rmSync(packageDirectory, {
    recursive: true,
    force: true,
  });
}

function preparePackageDirectory(packageDirectory, packageName) {
  removePreviouslyGeneratedPackage(packageDirectory);

  if (existsSync(packageDirectory)) {
    throw new Error(
      `Cannot generate ${packageName}: ${packageDirectory} already exists and was not generated by assemble.mjs.`,
    );
  }

  ensureDirectory(packageDirectory);
}

function createBasePackageJson(module, version) {
  return {
    name: module.packageName,
    version,
    type: "module",
    sideEffects: false,
    files: ["dist"],
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
    },
    scripts: {
      build: "vite build && tsc -p tsconfig.json",
    },
    publishConfig: {
      access: "public",
    },
    license: "MIT",
    homepage: homepageFromModulePath(module.modulePath),
    repository: {
      type: "git",
      url: "git+https://github.com/graphieros/raindrops-on-roses.git",
      directory: `packages/${module.packageSlug}`,
    },
  };
}

function createTsConfig() {
  return {
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      rootDir: "./src",
      outDir: "./dist",
      emitDeclarationOnly: true,
    },
    include: ["src/**/*.ts"],
    exclude: ["test", "dist"],
  };
}

function createViteConfig() {
  return `import { createLibraryConfig } from "../../config/vite.library.js";

export default createLibraryConfig(import.meta.dirname);
`;
}

function writeGeneratedMarker(packageDirectory) {
  writeFileSync(
    resolve(packageDirectory, GENERATED_MARKER),
    "Generated by scripts/assemble.mjs. Do not edit this package directly.\n",
  );
}

function generateLeafPackage(module, version) {
  const packageDirectory = resolve(PACKAGES_DIR, module.packageSlug);

  preparePackageDirectory(packageDirectory, module.packageName);

  const sourceDirectory = resolve(packageDirectory, "src");

  ensureDirectory(sourceDirectory);

  copyFileSync(
    resolve(module.directory, "src", "index.ts"),
    resolve(sourceDirectory, "index.ts"),
  );

  const readmeFile = resolve(module.directory, "README.md");

  if (existsSync(readmeFile)) {
    copyFileSync(readmeFile, resolve(packageDirectory, "README.md"));
  }

  writeJson(
    resolve(packageDirectory, "package.json"),
    createBasePackageJson(module, version),
  );

  writeJson(resolve(packageDirectory, "tsconfig.json"), createTsConfig());

  writeFileSync(
    resolve(packageDirectory, "vite.config.ts"),
    createViteConfig(),
  );

  writeGeneratedMarker(packageDirectory);
}

function getDirectChildren(aggregate, leaves, aggregates) {
  const prefix = `${aggregate.modulePath}/`;

  const children = [...leaves, ...aggregates].filter((candidate) => {
    if (!candidate.modulePath.startsWith(prefix)) {
      return false;
    }

    const remainder = candidate.modulePath.slice(prefix.length);

    return !remainder.includes("/");
  });

  return children.sort((a, b) => a.packageName.localeCompare(b.packageName));
}

function createAggregateSource(children) {
  return `${children
    .map((child) => `export * from "${child.packageName}";`)
    .join("\n")}\n`;
}

function createAggregateReadme(module, children) {
  const packageList = children
    .map((child) => `- \`${child.packageName}\``)
    .join("\n");

  return `# ${module.packageName}

Aggregate package for the \`${module.modulePath}\` module tree in [raindrops-on-roses](https://www.npmjs.com/package/raindrops-on-roses).

## Install

\`\`\`sh
npm install ${module.packageName}
\`\`\`

## Usage

\`\`\`ts
import { /* utilities */ } from "${module.packageName}";
\`\`\`

## Included packages

${packageList}

## Complete library

You can also install the complete library:

\`\`\`sh
npm install raindrops-on-roses
\`\`\`

## Repository

[graphieros/raindrops-on-roses](https://github.com/graphieros/raindrops-on-roses)
`;
}

function generateAggregatePackage(
  module,
  version,
  leaves,
  aggregates,
  versions,
) {
  const packageDirectory = resolve(PACKAGES_DIR, module.packageSlug);

  preparePackageDirectory(packageDirectory, module.packageName);

  const sourceDirectory = resolve(packageDirectory, "src");

  ensureDirectory(sourceDirectory);

  const children = getDirectChildren(module, leaves, aggregates);

  if (children.length === 0) {
    throw new Error(
      `Aggregate ${module.packageName} does not have any direct child packages.`,
    );
  }

  writeFileSync(
    resolve(sourceDirectory, "index.ts"),
    createAggregateSource(children),
  );

  writeFileSync(
    resolve(packageDirectory, "README.md"),
    createAggregateReadme(module, children),
  );

  const packageJson = createBasePackageJson(module, version);

  packageJson.dependencies = Object.fromEntries(
    children.map((child) => {
      const childVersion = versions[child.packageName];

      if (!childVersion) {
        throw new Error(`Missing version for ${child.packageName}.`);
      }

      return [child.packageName, childVersion];
    }),
  );

  writeJson(resolve(packageDirectory, "package.json"), packageJson);

  writeJson(resolve(packageDirectory, "tsconfig.json"), createTsConfig());

  writeFileSync(
    resolve(packageDirectory, "vite.config.ts"),
    createViteConfig(),
  );

  writeGeneratedMarker(packageDirectory);
}

function getTopLevelAggregates(aggregates) {
  return aggregates
    .filter((aggregate) => !aggregate.modulePath.includes("/"))
    .sort((a, b) => a.packageName.localeCompare(b.packageName));
}

function createUmbrellaSource(children) {
  return `${children
    .map((child) => `export * from "${child.packageName}";`)
    .join("\n")}\n`;
}

function homepageFromModulePath(modulePath) {
  return `${config.website}/${modulePath}`;
}

function generateUmbrellaPackage(version, aggregates, versions) {
  const packageName = config.umbrella.name;
  const packageDirectory = resolve(PACKAGES_DIR, packageName);

  preparePackageDirectory(packageDirectory, packageName);

  const children = getTopLevelAggregates(aggregates);

  if (children.length === 0) {
    throw new Error(
      "Cannot generate umbrella package: no top-level aggregate packages were found.",
    );
  }

  const sourceDirectory = resolve(packageDirectory, "src");

  ensureDirectory(sourceDirectory);

  writeFileSync(
    resolve(sourceDirectory, "index.ts"),
    createUmbrellaSource(children),
  );

  const packageJson = {
    name: packageName,
    version,
    type: "module",
    sideEffects: false,
    files: ["dist"],
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
    },
    scripts: {
      build: "vite build && tsc -p tsconfig.json",
    },
    dependencies: Object.fromEntries(
      children.map((child) => {
        const childVersion = versions[child.packageName];

        if (!childVersion) {
          throw new Error(`Missing version for ${child.packageName}.`);
        }

        return [child.packageName, childVersion];
      }),
    ),
    publishConfig: {
      access: "public",
    },
    license: "MIT",
    homepage: config.website,
    repository: {
      type: "git",
      url: "git+https://github.com/graphieros/raindrops-on-roses.git",
      directory: `packages/${packageName}`,
    },
  };

  writeJson(resolve(packageDirectory, "package.json"), packageJson);

  writeJson(resolve(packageDirectory, "tsconfig.json"), createTsConfig());

  writeFileSync(
    resolve(packageDirectory, "vite.config.ts"),
    createViteConfig(),
  );

  const rootReadme = resolve(ROOT_DIR, config.umbrella.readme);

  if (existsSync(rootReadme)) {
    copyFileSync(rootReadme, resolve(packageDirectory, "README.md"));
  }

  writeGeneratedMarker(packageDirectory);
}

function updateVersions(modules, versions) {
  let changed = false;

  for (const module of modules) {
    if (versions[module.packageName]) {
      continue;
    }

    versions[module.packageName] = config.initialVersion;
    changed = true;
  }

  if (!changed) {
    return;
  }

  const sorted = Object.fromEntries(
    Object.entries(versions).sort(([a], [b]) => a.localeCompare(b)),
  );

  writeJson(VERSIONS_FILE, sorted);
}

function main() {
  if (!existsSync(MODULES_DIR)) {
    throw new Error(
      `Modules directory does not exist: ${config.modulesDirectory}`,
    );
  }

  if (!existsSync(VERSIONS_FILE)) {
    throw new Error("Could not find packages.versions.json.");
  }

  const leaves = discoverLeafModules();
  const aggregates = discoverAggregateModules();

  if (leaves.length === 0) {
    throw new Error("No leaf modules were found.");
  }

  const umbrella = {
    packageName: config.umbrella.name,
  };

  const allModules = [...leaves, ...aggregates, umbrella];

  const versions = readJson(VERSIONS_FILE);

  updateVersions(allModules, versions);

  const updatedVersions = readJson(VERSIONS_FILE);

  console.log("");
  console.log("Assembling leaf packages:");
  console.log("");

  for (const module of leaves) {
    const version =
      updatedVersions[module.packageName] ?? config.initialVersion;

    generateLeafPackage(module, version);

    console.log(`  ${module.packageName}@${version} <- ${module.modulePath}`);
  }

  console.log("");

  if (aggregates.length > 0) {
    console.log("Assembling aggregate packages:");
    console.log("");

    const deepestFirst = [...aggregates].sort(
      (a, b) => b.modulePath.split("/").length - a.modulePath.split("/").length,
    );

    for (const module of deepestFirst) {
      const version =
        updatedVersions[module.packageName] ?? config.initialVersion;

      generateAggregatePackage(
        module,
        version,
        leaves,
        aggregates,
        updatedVersions,
      );

      console.log(`  ${module.packageName}@${version} <- ${module.modulePath}`);
    }
  }

  console.log("");
  console.log("Assembling umbrella package:");
  console.log("");

  const umbrellaVersion =
    updatedVersions[config.umbrella.name] ?? config.initialVersion;

  generateUmbrellaPackage(umbrellaVersion, aggregates, updatedVersions);

  console.log(`  ${config.umbrella.name}@${umbrellaVersion}`);
  console.log(
    `Generated ${leaves.length} leaf package(s), ${aggregates.length} aggregate package(s), and 1 umbrella package.`,
  );
}

try {
  main();
} catch (error) {
  console.error("");
  console.error("Failed to assemble packages.");

  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(error);
  }

  process.exit(1);
}
